### ISSUE TITLE
Switching off cache during backup

### ISSUE THREAD

**Issue by drequivalent** [facebook/flashcache#200]
We've been switching off flashcache globally during full-disk backup for quite a while now, to prevent SSD health wear-off. Then it got us thinking: does it even make any sense to do it?
How drastically does one Rsync pass wear an SSD off? Do the files get into cache as soon as they are being read, or does it have to be read several times?
Or is it more sensible to use flashcache blacklist in order to prevent Rsync from caching?

**Comment by mohans** [comment]
The right way to do this is to blacklist rsync to prevent the reads issued by rsync from being cached. Without doing that, the reads will get cached in flash on the very first miss, wearing out the SSD. If you could write a quick and dirty wrapper around rsync to get the pid and add it to the blacklist, and then delete it when rsync is done, you can leave flashcache enabled while backups are going on.

**Comment by drequivalent** [comment]
Thans for the answer.
Also, how do I find out, which processes are already in the flashcache black list?

**Comment by mohans** [comment]
/proc/flashcache/pidlists

**Comment by drequivalent** [comment]
* `/proc/flashcache/<device_pair>/flashcache_pidlists` , right?

**Comment by mohans** [comment]
Yes. That is it...

**Comment by drequivalent** [comment]
Okay, thanks.

**Comment by drequivalent** [comment]
I also noticed that the performance of Rsync with cache off (cache_all=0) is drastically better than perfomance of Rsync in blacklist and cache on (cache_all=1). Is this a normal behavior? What is even going on here?

**Comment by mohans** [comment]
It is possible that not all rsync related threads are blacklisted - causing some rsync IOs to get cached.

**Comment by drequivalent** [comment]
First, all rsync processes are blacklisted. Second, if something gets cached, it should be faster, not slower, right?

**Comment by drequivalent** [comment]
Sorry, that was my fault, got nothing to do with flashcache per se.
Thanks for the answers, you're awesome. Case closed.

**Comment by krichter722** [comment]
You should close the issue.
