### ISSUE TITLE
[Question] Can you manually flush the cache?

### ISSUE THREAD

**Issue by haneefmubarak** [facebook/flashcache#207]
@mohans I was wondering, if you use the writeback caching mode, can you manually flush the SSD cache to disk somehow (ie: running some sort of command)?

Alternatively, does flashcache automatically flush the SSD cache to disk upon shutdown? Can it be configured to do so?

**Comment by robertoalcantara** [comment]
Do you mean move all dirty blocks from SSD to disk?

Just set 1 to dev.flashcache.<cachedev>.do_sync parameter.

Check https://github.com/facebook/flashcache/blob/master/doc/flashcache-sa-guide.txt for more options.

**Comment by haneefmubarak** [comment]
Damn @robertoalcantara that was fast. Thanks, that'll do exactly what I had in mind!

**Comment by mohans** [comment]
Haneef to answer the second question. The default behavior is to sync all dirty blocks to disk on shutdown (unless the fast_shutdown sysctl is set).

**Comment by haneefmubarak** [comment]
Perfect!

Thanks @mohans!
